version: 2
jobs:
  build:
    docker:
      - image: amazonlinux

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Python 3.6
          command: |
            yum -y update
            yum -y install yum-utils
            yum -y groupinstall development
            yum -y install https://centos7.iuscommunity.org/ius-release.rpm
            yum -y install python36u
            yum -y install python36u-pip
            yum -y install python36u-devel

      - run:
          name: Install AWS CLI
          command: |
            pip install awscli

      - run:
          name: Install Hugo
          command: |
            cp hugo_installation_config.txt /etc/yum.repos.d/CentOS-hugo.repo
            yum install -y hugo
            hugo version
